export const chatActionTypes = {
  INPUT_SUCCESS: "INPUT_SUCCESS",
  INPUT_FAIL: "INPUT_FAIL",
  SESSION_SUCCESS: "SESSION_SUCCESS",
  SESSION_FAIL: "SESSION_FAIL",
  MESSAGE_SUCCESS: "MESSAGE_SUCCESS",
  MESSAGE_FAIL: "MESSAGE_FAIL",
};
