export const orderActionTypes = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",
};

export const orderActionDetailsTypes = {
  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAIL: "ORDER_DETAILS_FAIL",
};

export const orderActionPayTypes = {
  ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAIL: "ORDER_PAY_FAIL",
  ORDER_PAY_RESET: "ORDER_PAY_RESET",
};

export const orderActionMyOrderTypes = {
  ORDER_LIST_MY_REQUEST: "ORDER_LIST_MY_REQUEST",
  ORDER_LIST_MY_SUCCESS: "ORDER_LIST_MY_SUCCESS",
  ORDER_LIST_MY_FAIL: "ORDER_LIST_MY_FAIL",
  ORDER_LIST_MY_RESET: "ORDER_LIST_MY_RESET",
};

export const orderActionGetTypes = {
  ORDER_GET_REQUEST: "ORDER_GET_REQUEST",
  ORDER_GET_SUCCESS: "ORDER_GET_SUCCESS",
  ORDER_GET_FAIL: "ORDER_GET_FAIL",
};

export const orderActionDeliverTypes = {
  ORDER_DELIVER_REQUEST: "ORDER_DELIVER_REQUEST",
  ORDER_DELIVER_SUCCESS: "ORDER_DELIVER_SUCCESS",
  ORDER_DELIVER_FAIL: "ORDER_DELIVER_FAIL",
  ORDER_DELIVER_RESET: "ORDER_DELIVER_RESET",
};


