export const productActionTypes = {
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_FAILURE: "PRODUCT_LIST_FAILURE",
};

export const productDetailsActionTypes = {
  PRODUCT_DETAILS_LIST_REQUEST: "PRODUCT_DETAILS_LIST_REQUEST",
  PRODUCT_DETAILS_LIST_SUCCESS: "PRODUCT_DETAILS_LIST_SUCCESS",
  PRODUCT_DETAILS_LIST_FAILURE: "PRODUCT_DETAILS_LIST_FAILURE",
};

export const productActionDeleteTypes = {
  PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
  PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  PRODUCT_DELETE_FAILURE: "PRODUCT_DELETE_FAILURE",
};


