export const productActionTypes = {
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_FAILURE: "PRODUCT_LIST_FAILURE",
};

export const productDetailsActionTypes = {
  PRODUCT_DETAILS_LIST_REQUEST: "PRODUCT_DETAILS_LIST_REQUEST",
  PRODUCT_DETAILS_LIST_SUCCESS: "PRODUCT_DETAILS_LIST_SUCCESS",
  PRODUCT_DETAILS_LIST_FAILURE: "PRODUCT_DETAILS_LIST_FAILURE",
};

export const productActionDeleteTypes = {
  PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
  PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  PRODUCT_DELETE_FAILURE: "PRODUCT_DELETE_FAILURE",
};

export const productActionCreateTypes = {
  PRODUCT_CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
  PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",
  PRODUCT_CREATE_FAILURE: "PRODUCT_CREATE_FAILURE",
  PRODUCT_CREATE_RESET: "PRODUCT_CREATE_RESET",
};

export const productActionUpdateTypes = {
  PRODUCT_UPDATE_REQUEST: "PRODUCT_UPDATE_REQUEST",
  PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",
  PRODUCT_UPDATE_FAILURE: "PRODUCT_UPDATE_FAILURE",
  PRODUCT_UPDATE_RESET: "PRODUCT_UPDATE_RESET",
};

export const productActionReviewTypes = {
  PRODUCT_REVIEW_REQUEST: "PRODUCT_REVIEW_REQUEST",
  PRODUCT_REVIEW_SUCCESS: "PRODUCT_REVIEW_SUCCESS",
  PRODUCT_REVIEW_FAILURE: "PRODUCT_REVIEW_FAILURE",
  PRODUCT_REVIEW_RESET: "PRODUCT_REVIEW_RESET",
};


